# Default values for node projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: clementgohlke/keepsafe-frontend
  tag: 2
  pullPolicy: Always
