name: Release
on:
  push:
    branches:
      - master
jobs:
  build-frontend:
    name: build-frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
      - run: docker build . -t "clementgohlke/keepsafe-frontend:${{github.event.release.tag_name}}" 
      - run: docker login -u clementgohlke -p ${{secrets.DOCKER_HUB_TOKEN}}
      - run: docker push clementgohlke/keepsafe-frontend:${{ github.event.release.tag_name }}
